### ISSUE TITLE
./MindTheGap 'fill' takes too long time for WGS data

### ISSUE THREAD

**Issue by pinarkavak** [GATB/MindTheGap#1]
Hi,
I ran MindTheGap on a whole genome sequence data(30x, paired-end 101bp data). The 'find' part has ended in a reasonable time. I ran the 'fill' part similar to the following command: 

./MindTheGap fill -graph example.h5 -bkpt example.breakpoints -out example -max-memory 500000 -max-disk 1000000 -nb-cores 84

I increased the -max-memory, -max-disk, and -nb-cores just to speed up the process (The machine has 96 cores (I did not want to use all of the cores), 1TB memory, and more than 2TB disk space).

After ~4,5 - 5 hours, I get this message as time estimate:
[Filling breakpoints                     ]  1.03 %   elapsed: 288 min 1  sec   remaining: 27789 min 39 sec

which makes 19 more days! Am I doing something wrong? How can I speed up the 'fill' function?

Thank you very much for you help!

**Comment by clemaitre** [comment]
Hi,

thank you for the feedback.

The options -max-memory and -max-disk are only used for the graph construction part. In your case, the graph is already built (h5 file), therefore these options will not speed up the fill part. As for the -nb-cores option, unfortunately, this part is not yet parallelized... but we are currently implementing it, it should be available very soon (hopefully a matter of days).

If you can not wait, you can parallelize it "manually" : each breakpoint is filled independently from each other, therefore you can split your .breakpoints file in several parts and run the fill module for each part. Be carreful not to split a given breakpoint in two separate files (a breakpoint is defined by two consecutive fasta entries (4 lines) in the .breakpoint file).

Nevertheless, I am quite surprised by the estimated large amount of time. Either, the number of breakpoints you want to fill is very large, or each breakpoint is very long to fill because the graph is very complex. In the first case, does the number of breakpoints fit with your expectations of number of insertions in your data ? In the second case, you can check if the graph is of reasonable complexity (ie built with good parameters) : in the find output, you can check the number "nb_solid_kmers", it should be close to the size of your genome.

Regards,
Claire

**Comment by pinarkavak** [comment]
Hi Claire,

Thank you very much for your informative response. 

For the first case: I have ~232,000 breakpoints which is 3-4 times more than I expected but it is real data, so who knows may be my expectation is wrong. 
For the second case: The breakpoints are not very long but I checked the find output: 
nb_solid_kmers: 2496639829, 
I used human_v37 reference which is ~2.8billion (without Ns). So, they are close I guess. 

I will try to split the breakpoint file. 
Thank you very much for your help,
pinar

**Comment by rizkg** [comment]
Hi, 
MindTheGap  "fill" is now parallelized, you can get the last commit from the master branch  and try it out :

ae7ac9fdc2f5c3a4a1560879c84cd7dd0a87ffff

It should now create as many threads as provided by the  -nb-cores option and split internally the work among the list of breakpoints. The only difference is that the results in the output file will be in a random order.
Tell me if you encounter any problem,

Guillaume

**Comment by pinarkavak** [comment]
Thank you very much Guillaume!
