### ISSUE TITLE
EXCEPTION: Failure because of unhandled kmer size 128

### ISSUE THREAD

**Issue by matt-shenton** [GATB/MindTheGap#11]
Hi 

Thanks a lot for this great tool.

I wanted to try kmer size 128, but it seems not to work:

EXCEPTION: Failure because of unhandled kmer size 128

-kmer-size 96 works fine (using my real data, I can find a known breakpoint - although the insertion is too large to be assembled  (~9kb))

I tried both MindTheGap-v2.2.1-bin-Linux.tar.gz
and cloning from github.

Using Centos 7.

Thanks in advance for your help

Best wishes

Matt Shenton

**Comment by clemaitre** [comment]
Hi Matt,

thank you for using MindTheGap and for the feedback.

By default, the largest kmer-size allowed is 128. To use k>128, you will need to re-compile MindTheGap as follows:
```
cd build/
cmake -DKSIZE_LIST="32 64 96 256" ..
make
```
To go back to default, replace 256 by 128. 

Note also that with such a large k value you need a high sequencing coverage so that the de bruijn graph remains connected.

Also, if you know your insertion is large, you may try to increase the following options of the fill module:
* `-max-nodes`: maximum number of nodes in contig graph for each insertion assembly [default '100']. This arguments limits the computational time, increasing its value may be useful for complex genomes or long insertions.
* `-max-length`: maximum number of assembled nucleotides in the whole contig graph (nt) [default '10000']. This arguments limits the computational time, increasing its value may be useful for complex genomes or long insertions. 

Best regards,
Claire

**Comment by matt-shenton** [comment]
Dear Claire,

Many thanks for your reply.

I may have misunderstood the documentation but I was trying to use k=128, not k>128

The following works fine:
MindTheGap find -kmer-size 96 -in R1.fastq.gz,R2.fastq.gz -ref genome.fa -out results96

but the following does not:
MindTheGap find -kmer-size 128 -in R1.fastq.gz,R2.fastq.gz -ref genome.fa -out results128

and it fails with the message:
EXCEPTION: Failure because of unhandled kmer size 128

Thanks a lot

Matt

**Comment by clemaitre** [comment]
Dear Matt,

Sorry, I made a mistake in my first reply: in fact the largest kmer size allowed without re-compiling is 127, and for k larger or equal to 128, you have to re-compile MindTheGap with the command I gave previously.

Claire

**Comment by matt-shenton** [comment]
Dear Claire,

Many thanks for your reply. I understand now.

Best wishes

Matt Shenton
